# Generated by Django 3.0.8 on 2020-07-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200706_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateField(auto_now_add=True, help_text='YYYY-MM-DD'),
        ),
    ]
