# Generated by Django 3.0.8 on 2020-07-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200706_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateField(auto_now_add=True, help_text='YYYY-MM-DD-TT'),
        ),
    ]
